# Generated by Django 3.1.7 on 2021-03-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(max_length=500)),
                ('age', models.CharField(max_length=3)),
                ('residence', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('block1', models.TextField(max_length=150)),
                ('block2', models.TextField(max_length=150)),
                ('block3', models.TextField(max_length=150)),
                ('block4', models.TextField(max_length=150)),
                ('clients', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('projects', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(upload_to='bg_image/')),
                ('image', models.ImageField(upload_to='photo/')),
                ('name', models.CharField(max_length=30)),
                ('about_mini', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('subtitle1', models.CharField(max_length=30)),
                ('subtitle2', models.CharField(max_length=30)),
                ('subtitle3', models.CharField(max_length=30)),
                ('link_tg', models.URLField(blank=True, null=True)),
                ('link_inst', models.URLField(blank=True, null=True)),
                ('link_tweet', models.URLField(blank=True, null=True)),
                ('link_whatsapp', models.URLField(blank=True, null=True)),
                ('link_git', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
