# Generated by Django 3.1.7 on 2021-03-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cert/')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=150)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Qualities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.IntegerField(max_length=3)),
                ('second', models.IntegerField(max_length=3)),
                ('third', models.IntegerField(max_length=3)),
                ('fourth', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_design', models.IntegerField(max_length=3)),
                ('html_css', models.IntegerField(max_length=3)),
                ('python', models.IntegerField(max_length=3)),
                ('frameworks', models.IntegerField(max_length=3)),
            ],
        ),
    ]
