# Generated by Django 3.1.7 on 2021-03-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_certs_education_experience_qualities_skilllevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
